CREATE TABLE books (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255))ENGINE=INNODB;
CREATE TABLE autors (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255))ENGINE=INNODB;
CREATE TABLE library_refs (	books_id INT, 
				autors_id INT, 
				PRIMARY KEY (books_id ,autors_id ),
				FOREIGN KEY (books_id)  REFERENCES books  (id) ON DELETE CASCADE,
				FOREIGN KEY (autors_id) REFERENCES autors (id) ON DELETE CASCADE )ENGINE=INNODB;